name: CI

on:
  push:
    paths-ignore:
      - "**.md"
      - "contrib/*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 24.5
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - snapshot
        emacs_check:
          - package-lint
          - byte-compile
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: actions/checkout@v2
      - name: Run checks
        uses: leotaku/elisp-check@master
        with:
          file: "*.el"
          check: ${{ matrix.emacs_check }}
